---
key: ""
autoclaim: true

vote_announcement: "{username} has voted and received {reward} !"

message_not_voted: "§cYou haven't voted today"
message_voted: "§aYou have already voted today"


commands:
# parameters: {username} 
  - ""
...
